# Generated by Django 3.2 on 2024-11-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20241104_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
